"""Unit tests for recall channels (skipped until implementation lands)."""

from __future__ import annotations

import pytest

pytestmark = pytest.mark.skip(reason="Recall models scheduled for W1–W2.")


def test_als_fits_and_recalls() -> None: ...
def test_two_tower_embedding_dim() -> None: ...
def test_sasrec_respects_max_seq_len() -> None: ...
def test_popularity_returns_same_list_for_all_users() -> None: ...
def test_rrf_monotonicity() -> None: ...
